services: 
    docker-fastapi:
        container_name: docker-fastapi
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        restart: always
    docker-vite:
        depends_on: 
            - docker-fastapi
        container_name: docker-vite
        build: 
            context: ./frontend/
            args:
                - VITE_API_URL=/api
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
        